-- 7th 
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS hbtn_0d_usa.cities(id UNIQUE AUTO_INCREMENT PRIMARY KEY,state_id NOT NULL,name VARCHAR(256) NOT NULL,FOREIGN KEY(state_id) REFERENCES TO states(id));
